language: ruby
dist: trusty
cache: bundler

before_install:
  - gem install bundler
install:
  - bundle install

script:
  - jekyll doctor
  - jekyll build -V --no-watch --strict_front_matter

# Uncomment below when we register a domain
# deploy:
#   provider: pages
#   cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   on:
#     branch: master