# SEO
title: Mello
description: "Easing your mind whenever you need us."
author: "The Mello Team"
url: "https://getmello.org"

# Editing below isn't recommended :)

exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache

plugins:
  - jekyll
  - jekyll-sass-converter
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: _scss

permalink: pretty