title: Mello
description: "Easing your mind whenever you need us."
baseurl: "/"
url: "https://mello-app.github.io"

# Editing below isn't recommended :)

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll
  - jekyll-sass-converter
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: _scss

permalink: pretty