title: Mello
description: "Easing your mind whenever you need us."
baseurl: "/"
url: "https://mello-app.github.io"

nav:
  - title: "Home"
    url: "/"
  - title: "Team"
    url: "/team"
  - title: "GitHub"
    url: "https://github.com/mello-app"
  - title: "Download"
    url: "#download"

# Editing below isn't recommended :)

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll
  - jekyll-sass-converter
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: _sass

permalink: pretty